version: "3"

networks:
  grafana:

services:
  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo-config.yaml
      - ./volumes/tempo:/tmp/tempo
    command: -config.file=/etc/tempo-config.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    networks:
      - grafana

  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      # custom config will read logs from the containers of this project
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml
      # to read container labels and logs
      - ./logs:/var/dm-node/logs:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - grafana

  prometheus:
    image: prom/prometheus:latest
    command: 
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus-config.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  # k6-tracing:
  #   image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
  #   environment:
  #     - ENDPOINT=tempo:4317
  #   restart: always
  #   depends_on:
  #     - tempo
  #   networks:
  #     - grafana

  grafana:
    image: grafana/grafana:latest
    ports:
      - "8081:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      # directory must be created first, with uid:gid 472:472
      - ./volumes/grafana:/var/lib/grafana
      # automatically configure the all datasource
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - grafana
